### ISSUE TITLE
Merge workshop repo with nscale-docs

### ISSUE THREAD

**Issue by McDonnellDean** [nearform/nscale-workshop#36]
It might be useful to turn off the Github Wiki for this repo as it is in and of itself a wiki.

EDIT: Issue name has been changed to reflect the contents below, the original issue description has been left in tact.

**Comment by mcollina** [comment]
I would rather kill this repo and move everything to the nscale-docs repo.

@pelger @darragh-hayes what do you think?

**Comment by McDonnellDean** [comment]
I would agree with this. The new doc's repo supports folders so it wont impact the current usability of this repo. It would also mean all of nscale's docs would be in the one place to take offline.

**Comment by darragh-hayes** [comment]
Yeah I was thinking with this. Then in the README for the the docs repo we can do something like recommending by starting with the workshop. That kinda thing. Oh I've also changed every doc in the v0.14 branch to use relative links which means we can very easily move!

**Comment by mcollina** [comment]
I would call it 'tutorials' and not workshop now, the quality is really good at this point in time. I would like to have them (and the docs) in the website, and auto-generate them from the markdown files.

**Comment by McDonnellDean** [comment]
I second calling them tutorials and having that as a section on the Wiki, that way we are covering, installation, usage and API docs nicely. @mcollina where is the website housed? I shouldn't be a big job once we standardise out the flow of the repo to have a nice website based docs section. (automation FTW)

**Comment by mcollina** [comment]
A wiki is no good for these stuff, you want proper versioning, so you can have pull requests and so on. We started with a wiki and switched to a repo for this reason.

**Comment by McDonnellDean** [comment]
Yup, sorry I meant Docs Repo not wiki. I was the one who made the suggestion :D

**Comment by McDonnellDean** [comment]
@pelger has said he is happy to do this move once the current docs in nscale-docs are cleaned up and tidied over.

**Comment by mcollina** [comment]
:+1:

**Comment by mcollina** [comment]
I think this was done :)

@darragh-hayes can you please do a commit here saying this has been moved?

**Comment by darragh-hayes** [comment]
Indeed the workshop tutorials have been moved along with some housecleaning. See https://github.com/nearform/nscale-docs/pull/6
