### ISSUE TITLE
Change the repo's description to something more appropriate.

### ISSUE THREAD

**Issue by thekemkid** [nearform/nscale-workshop#40]
Nodeconf.eu was a while ago, it might be time for an update.

**Comment by darragh-hayes** [comment]
@mcollina can we get this changed to something more appropriate? "Tutorials for geting started with nscale" might suffice.

**Comment by McDonnellDean** [comment]
The plan is to kill this repo via merge with nscale-docs so I wouldn't worry to much about it

**Comment by McDonnellDean** [comment]
Closing this one as #36 concluded that this repo will be merged with nscale-docs and closed so there is not much need to dicky up place :D
